-- MySQL Script generated by MySQL Workbench
-- 12/15/18 11:40:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dunamis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dunamis` ;

-- -----------------------------------------------------
-- Schema dunamis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dunamis` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `dunamis` ;

-- -----------------------------------------------------
-- Table `tbl_planes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_planes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_planes` (
  `codigo_plan` INT NOT NULL AUTO_INCREMENT,
  `nombre_plan` VARCHAR(45) NOT NULL,
  `precio_plan` DECIMAL NOT NULL,
  PRIMARY KEY (`codigo_plan`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_paises` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_paises` (
  `codigo_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_pais`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_tipo_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_tipo_usuario` (
  `codigo_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_tipo_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_usuarios` (
  `codigo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(200) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `descripcion` VARCHAR(200) NULL,
  `direccion` VARCHAR(200) NULL,
  `foto` VARCHAR(80) NULL,
  `fecha_nacimiento` DATE NULL,
  `codigo_plan` INT NOT NULL,
  `codigo_pais` INT NOT NULL,
  `codigo_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_creditos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_creditos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_creditos` (
  `codigo_credito` INT NOT NULL AUTO_INCREMENT,
  `numero_tarjeta` VARCHAR(100) NOT NULL,
  `mes_vence` VARCHAR(45) NOT NULL,
  `anio_vence` VARCHAR(45) NOT NULL,
  `codigo_seguridad` VARCHAR(10) NOT NULL,
  `codigo_plan` INT NOT NULL,
  PRIMARY KEY (`codigo_credito`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_proyectos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_proyectos` (
  `codigo_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  `codigo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_proyecto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_archivo_html`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_archivo_html` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_archivo_html` (
  `codigo_archivo_html` INT NOT NULL AUTO_INCREMENT,
  `nombre_archivo_html` LONGBLOB NULL,
  `codigo_proyecto` INT NOT NULL,
  PRIMARY KEY (`codigo_archivo_html`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_archivo_css`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_archivo_css` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_archivo_css` (
  `codigo_archivo_css` INT NOT NULL AUTO_INCREMENT,
  `nombre_archivo_css` LONGBLOB NULL,
  `codigo_proyecto` INT NOT NULL,
  PRIMARY KEY (`codigo_archivo_css`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_archivo_js`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_archivo_js` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_archivo_js` (
  `codigo_archivo_js` INT NOT NULL AUTO_INCREMENT,
  `nombre_archivo_js` LONGBLOB NULL,
  `codigo_proyecto` INT NOT NULL,
  PRIMARY KEY (`codigo_archivo_js`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_continentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_continentes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_continentes` (
  `codigo_continente` INT NOT NULL AUTO_INCREMENT,
  `nombre_continente` VARCHAR(45) NOT NULL,
  `codigo_pais` INT NOT NULL,
  PRIMARY KEY (`codigo_continente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_estados_deptos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_estados_deptos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_estados_deptos` (
  `codigo_estado_depto` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_depto` VARCHAR(45) NOT NULL,
  `codigo_pais` INT NOT NULL,
  PRIMARY KEY (`codigo_estado_depto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_mensajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_mensajes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_mensajes` (
  `codigo_mensaje` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `codigo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_mensaje`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_facebook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_facebook` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_facebook` (
  `codigo_facebook` INT NOT NULL AUTO_INCREMENT,
  `url_facebook` VARCHAR(100) NULL,
  `codigo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_facebook`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_twitter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_twitter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_twitter` (
  `codigo_twitter` INT NOT NULL AUTO_INCREMENT,
  `url_twitter` VARCHAR(100) NULL,
  `codigo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_twitter`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_linkedin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_linkedin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_linkedin` (
  `codigo_linkedin` INT NOT NULL AUTO_INCREMENT,
  `url_linkedin` VARCHAR(100) NULL,
  `codigo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_linkedin`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_github`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_github` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_github` (
  `codigo_github` INT NOT NULL AUTO_INCREMENT,
  `url_github` VARCHAR(100) NULL,
  `codigo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_github`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_usuarios_x_tbl_proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuarios_x_tbl_proyectos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_usuarios_x_tbl_proyectos` (
  `codigo_usuario` INT NOT NULL,
  `codigo_proyecto` INT NOT NULL,
  PRIMARY KEY (`codigo_usuario`, `codigo_proyecto`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
